version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
  web:
    build: .
    command: sh "init_db.sh"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db