version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    environment:
      - APP_DB_HOST=${APP_DB_HOST}
      - APP_DB_DATABASE=${APP_DB_DATABASE}
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    depends_on:
      - db